### ISSUE TITLE
滑到地圖區就很難回去了

### ISSUE THREAD

**Issue by aviatorraum** [orora-foodmate/foodmate-app#69]

**Comment by aviatorraum** [comment]
點擊地址打開google map

### [open google map](https://developers.google.com/maps/documentation/urls/get-started)
* search location: https://www.google.com/maps/search/?api=1&{{parameters}}
  * ```&query=city+center``` => &query={第一關鍵字}＋{第二關鍵字} 
  * ```&query=47.5951518,-122.3316393&query_place_id=ChIJKxjxuaNqkFQR3CK6O1HNNqY``` => &query={精度}+{緯度}&query_place_id={地點id}

**Comment by teraui41** [comment]
移除 google map webview, 改用點擊方式打開
